version: 2.1
jobs:

  test-python:
    docker:
      - image: ocrd/core-cuda-tf1
    environment:
      PIP: pip3
      PYTHON: python3
    steps:
      - checkout
      - run: sudo apt-get install -y hunspell hunspell-de-de
      - run: make deps deps-test
      - run: make install
      # restore pretrained model from previous download
      - restore_cache:
          key: v0.1-model-s2s.dta19.Fraktur4.d2.w0512
      - run: mkdir test-results
      - run:
          name: Test with pytest and measure code coverage
          # isolate tests so memory from loaded model gets freed in between
          command: make coverage PYTEST_ARGS="-vv --isolate --junitxml=test-results/pytest.xml"
          no_output_timeout: 59m
      - save_cache:
          key: v0.1-model-s2s.dta19.Fraktur4.d2.w0512
          paths:
            - models
      - run:
          name: Generate coverage reports
          command: |
            coverage html -d test-results
            coverage json -o test-results/coverage.json
            coverage xml -o test-results/coverage.xml
      - store_test_results:
          path: test-results/pytest.xml
      - store_artifacts:
          path: test-results
      - run:
          name: Upload to Codecov.io
          command: |
            sudo apt-get install -y g++
            pip install codecov-cli
            codecovcli --auto-load-params-from CircleCI --verbose upload-process -t "$CODECOV_TOKEN" -n "$CIRCLE_JOB" --build-url "$CIRCLE_BUILD_URL" --build-code "$CIRCLE_BUILD_NUM" -B "$CIRCLE_BRANCH" --dir test-results
    resource_class: large

  build-docker:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run: make docker
    resource_class: large

  deploy-docker:
    docker:
      - image: circleci/buildpack-deps
    steps:
      - checkout
      - setup_remote_docker: # https://circleci.com/docs/2.0/building-docker-images/
          docker_layer_caching: true
      - run: make docker
      - run:
          name: Login to Docker Hub
          command: echo "$DOCKERHUB_PASS" | docker login --username "$DOCKERHUB_USER" --password-stdin
      - run: docker push ocrd/cor-asv-ann

  deploy-pypi:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run: pip install -U twine build packaging
      - run: make build
      - run: twine upload dist/*

workflows:
  version: 2
  build-and-test:
    jobs:
      - test-python
      - build-docker
  deploy:
    jobs:
      - deploy-docker:
          filters:
            branches:
              only: master
      - deploy-pypi:
          filters:
            branches:
              only: master
