version: 2.1
jobs:

  build-python3:
    docker:
      - image: ocrd/core
    environment:
      PIP: pip3
      PYTHON: python3
    steps:
      - run: apt-get update && apt-get install -y --no-install-recommends make git
      # workaround for tensorflow-gpu not being available on PyPI anymore:
      # get nvidia-tensorflow from nvidia-pyindex and repackage it as tensorflow-gpu
      - run: |
          git clone https://github.com/OCR-D/ocrd_all /tmp/ocrd_all && \
          make -f <(echo new:; echo ' $(pip_install_tf1nvidia)') -f /tmp/ocrd_all/Makefile new SEMPIP=
      - checkout
      - run: make deps
      - run: make install

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-python3
