version: 2.1
jobs:

  build-python3:
    docker:
      - image: ocrd/core-cuda-tf1
    environment:
      PIP: pip3
      PYTHON: python3
    steps:
      - checkout
      - run: make deps
      - run: make install

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-python3
