version: 2.1
jobs:

  build-python3:
    docker:
      - image: ocrd/core-cuda-tf1
    environment:
      PIP: pip3
      PYTHON: python3
    steps:
      - checkout
      - run: make deps
      - run: make install

  deploy-docker:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker: # https://circleci.com/docs/2.0/building-docker-images/
          docker_layer_caching: true
      - run: make docker
      - run:
          name: Login to Docker Hub
          command: echo "$DOCKERHUB_PASS" | docker login --username "$DOCKERHUB_USER" --password-stdin
      - run: docker push ocrd/cor-asv-ann
      
workflows:
  version: 2
  build-and-test:
    jobs:
      - build-python3
  deploy:
    jobs:
      - deploy-docker:
          filters:
            branches:
              only: master
